# EDA Marketing History

Черновой ноутбук. Добавляйте код и выводы по мере анализа.

In [16]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [17]:
marketing = pd.read_excel(
    "../data/raw/marketing_history.xlsx",
    header=2
)

print("Размер данных:", marketing.shape)
marketing.head()

Размер данных: (210, 40)

,event_id,event_time,source_channel,activity_type,course,campaign,placement,creative_text,external_or_internal,post_url,...,raw_ad_marking,raw_erid,raw_scraped_at,raw_html_ref,Unnamed: 34,product_scope,product_line,inferred_course,content_direction,candidate_courses
0,INT-1764,2026-07-01 18:10:49,@postypashki_old,Контент с предложением курсов (авто),ML старт | Data Science,NaN,postypashki_old/1764,Самые интересные события в ближайшее время.\nВ...,internal,https://t.me/postypashki_old/1764,...,NaN,False,2026-07-01T15:10:49+00:00,NaN,NaN,multiple_courses,START,NaN,career,ML старт | Data science
1,INT-1765,2026-07-02 18:31:22,@postypashki_old,Прочий контент (авто),NaN,NaN,postypashki_old/1765,"В новом ролике обсудим, что с вашей психикой с...",internal,https://t.me/postypashki_old/1765,...,NaN,False,2026-07-02T15:31:22+00:00,NaN,NaN,unknown,NaN,NaN,career,NaN
2,INT-1767,2026-07-04 12:03:55,@postypashki_old,Промо со скидкой (авто),NaN,NaN,postypashki_old/1767,❗️ Завтра заканчивается донабор на стажировку ...,internal,https://t.me/postypashki_old/1767,...,NaN,False,2026-07-04T09:03:55+00:00,NaN,NaN,product_line,START,NaN,career,Аналитика старт | Алгоритмы старт | Backend ст...
3,INT-1768,2026-07-04 15:35:53,@postypashki_old,Контент с предложением курсов (авто),ML старт,NaN,postypashki_old/1768,Академия Авито и Буткем Авито \n\nСегодня прош...,internal,https://t.me/postypashki_old/1768,...,NaN,False,2026-07-04T12:35:53+00:00,NaN,NaN,single_course,START,ML старт,ml,ML старт
4,INT-1770,2026-07-05 16:51:14,@postypashki_old,Прочий контент (авто),ML старт,NaN,postypashki_old/1770,Как затащить МЛ собеседование в 2026 году \n\n...,internal,https://t.me/postypashki_old/1770,...,NaN,False,2026-07-05T13:51:14+00:00,NaN,NaN,single_course,START,ML старт,ml,ML старт

In [18]:
# Убираем полностью пустые столбцы
marketing = marketing.dropna(axis=1, how="all")

print("Размер после очистки:", marketing.shape)
marketing.head()

Размер после очистки: (210, 38)

,event_id,event_time,source_channel,activity_type,course,placement,creative_text,external_or_internal,post_url,views,...,raw_ad_marking,raw_erid,raw_scraped_at,raw_html_ref,Unnamed: 34,product_scope,product_line,inferred_course,content_direction,candidate_courses
0,INT-1764,2026-07-01 18:10:49,@postypashki_old,Контент с предложением курсов (авто),ML старт | Data Science,postypashki_old/1764,Самые интересные события в ближайшее время.\nВ...,internal,https://t.me/postypashki_old/1764,21200,...,NaN,False,2026-07-01T15:10:49+00:00,NaN,NaN,multiple_courses,START,NaN,career,ML старт | Data science
1,INT-1765,2026-07-02 18:31:22,@postypashki_old,Прочий контент (авто),NaN,postypashki_old/1765,"В новом ролике обсудим, что с вашей психикой с...",internal,https://t.me/postypashki_old/1765,17500,...,NaN,False,2026-07-02T15:31:22+00:00,NaN,NaN,unknown,NaN,NaN,career,NaN
2,INT-1767,2026-07-04 12:03:55,@postypashki_old,Промо со скидкой (авто),NaN,postypashki_old/1767,❗️ Завтра заканчивается донабор на стажировку ...,internal,https://t.me/postypashki_old/1767,18600,...,NaN,False,2026-07-04T09:03:55+00:00,NaN,NaN,product_line,START,NaN,career,Аналитика старт | Алгоритмы старт | Backend ст...
3,INT-1768,2026-07-04 15:35:53,@postypashki_old,Контент с предложением курсов (авто),ML старт,postypashki_old/1768,Академия Авито и Буткем Авито \n\nСегодня прош...,internal,https://t.me/postypashki_old/1768,20400,...,NaN,False,2026-07-04T12:35:53+00:00,NaN,NaN,single_course,START,ML старт,ml,ML старт
4,INT-1770,2026-07-05 16:51:14,@postypashki_old,Прочий контент (авто),ML старт,postypashki_old/1770,Как затащить МЛ собеседование в 2026 году \n\n...,internal,https://t.me/postypashki_old/1770,19000,...,NaN,False,2026-07-05T13:51:14+00:00,NaN,NaN,single_course,START,ML старт,ml,ML старт

In [24]:
marketing = marketing.drop(columns=["Unnamed: 34"])

In [25]:
marketing.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 210 entries, 0 to 209
Data columns (total 37 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   event_id              210 non-null    object
 1   event_time            210 non-null    datetime64[ns]
 2   source_channel        210 non-null    object
 3   activity_type         210 non-null    object
 4   course                35 non-null     object
 5   placement             210 non-null    object
 6   creative_text         193 non-null    object
 7   external_or_internal  210 non-null    object
 8   post_url              210 non-null    object
 9   views                 210 non-null    int64
 10  reactions             189 non-null    float64
 11  data_source           210 non-null    object
 12  confidence            210 non-null    object
 13  collected_by          210 non-null    object
 14  notes                 210 non-null    object
 15  channel_relationship  210 non-null    object
 16  paid_status           210 non-null    object
 17  raw_origin            210 non-null    object
 18  raw_category          210 non-null    object
 19  raw_period            97 non-null     object
 20  raw_media             47 non-null     object
 21  raw_forwarded_from    49 non-null     object
 22  raw_links             113 non-null    object
 23  raw_promo_candidate   113 non-null    float64
 24  raw_offer_flag        97 non-null     float64
 25  raw_discount_flag     97 non-null     float64
 26  raw_launch_flag       97 non-null     float64
 27  raw_lead_magnet_flag  97 non-null     float64
 28  raw_ad_marking        3 non-null      object
 29  raw_erid              210 non-null    object
 30  raw_scraped_at        97 non-null     object
 31  raw_html_ref          113 non-null    object
 32  product_scope         210 non-null    object
 33  product_line          109 non-null    object
 34  inferred_course       87 non-null     object
 35  content_direction     210 non-null    object
 36  candidate_courses     114 non-null    object
dtypes: datetime64[ns](1), float64(6), int64(1), object(29)
memory usage: 60.8+ KB

In [26]:
marketing["event_time"] = pd.to_datetime(
    marketing["event_time"],
    errors="coerce"
)

print("Период данных:")
print(marketing["event_time"].min(), "—", marketing["event_time"].max())

Период данных:
2026-07-01 18:10:49 — 2026-09-10 17:36:13

In [27]:
categorical_cols = [
    "source_channel",
    "activity_type",
    "external_or_internal",
    "data_source",
    "confidence",
    "channel_relationship",
    "paid_status"
]

for col in categorical_cols:
    print(f"\n### {col}")
    display(marketing[col].value_counts(dropna=False))

### source_channel

source_channel
@postypashki_old     97
@chad_protocol       21
@ProdAnalysis        20
@zadachi_ds          19
@codeof_art          16
@postypashki_mems    16
@algoses             12
@matesha_shad         9
Name: count, dtype: int64

### activity_type

activity_type
Продвижение курсов / промо (кандидат по тексту)    80
Контент с предложением курсов (авто)               36
Прочий контент (авто)                              23
Бесплатное событие / лид-магнит                    12
Контент со ссылкой / упоминанием                   12
Медиа без текста / нужна проверка                  11
Бесплатное событие / лид-магнит (авто)             10
Пересылка / контентное упоминание                   9
Рекламная маркировка / проверить направление        8
Промо со скидкой (авто)                             6
Запуск / набор (авто)                               3
Name: count, dtype: int64

### external_or_internal

external_or_internal
external    113
internal     97
Name: count, dtype: int64

### data_source

data_source
Telegram    210
Name: count, dtype: int64

### confidence

confidence
raw    210
Name: count, dtype: int64

### channel_relationship

channel_relationship
unknown     113
internal     97
Name: count, dtype: int64

### paid_status

paid_status
unknown    210
Name: count, dtype: int64

In [29]:
marketing["product_scope"].value_counts(dropna=False)

product_scope
single_course       55
unknown             49
product_line        42
multiple_courses    34
general_brand       22
external             8
Name: count, dtype: int64