# EDA Marketing History

Черновой ноутбук. Добавляйте код и выводы по мере анализа.

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [4]:
marketing = pd.read_excel(
    "../data/raw/marketing_history.xlsx",
    header=2
)

print("Размер данных:", marketing.shape)
marketing.head()

Размер данных: (210, 35)

,event_id,event_time,source_channel,activity_type,course,campaign,placement,creative_text,external_or_internal,post_url,...,raw_promo_candidate,raw_offer_flag,raw_discount_flag,raw_launch_flag,raw_lead_magnet_flag,raw_ad_marking,raw_erid,raw_scraped_at,raw_html_ref,Unnamed: 34
0,INT-1764,2026-07-01 18:10:49,@postypashki_old,Контент с предложением курсов (авто),ML старт | Data Science,NaN,postypashki_old/1764,Самые интересные события в ближайшее время.\nВ...,internal,https://t.me/postypashki_old/1764,...,NaN,1.0,0.0,0.0,0.0,NaN,False,2026-07-01T15:10:49+00:00,NaN,NaN
1,INT-1765,2026-07-02 18:31:22,@postypashki_old,Прочий контент (авто),NaN,NaN,postypashki_old/1765,"В новом ролике обсудим, что с вашей психикой с...",internal,https://t.me/postypashki_old/1765,...,NaN,0.0,0.0,0.0,0.0,NaN,False,2026-07-02T15:31:22+00:00,NaN,NaN
2,INT-1767,2026-07-04 12:03:55,@postypashki_old,Промо со скидкой (авто),NaN,NaN,postypashki_old/1767,❗️ Завтра заканчивается донабор на стажировку ...,internal,https://t.me/postypashki_old/1767,...,NaN,1.0,1.0,0.0,0.0,NaN,False,2026-07-04T09:03:55+00:00,NaN,NaN
3,INT-1768,2026-07-04 15:35:53,@postypashki_old,Контент с предложением курсов (авто),ML старт,NaN,postypashki_old/1768,Академия Авито и Буткем Авито \n\nСегодня прош...,internal,https://t.me/postypashki_old/1768,...,NaN,1.0,0.0,0.0,0.0,NaN,False,2026-07-04T12:35:53+00:00,NaN,NaN
4,INT-1770,2026-07-05 16:51:14,@postypashki_old,Прочий контент (авто),ML старт,NaN,postypashki_old/1770,Как затащить МЛ собеседование в 2026 году \n\n...,internal,https://t.me/postypashki_old/1770,...,NaN,0.0,1.0,0.0,0.0,NaN,False,2026-07-05T13:51:14+00:00,NaN,NaN

In [5]:
# Убираем полностью пустые столбцы
marketing = marketing.dropna(axis=1, how="all")

print("Размер после очистки:", marketing.shape)
marketing.head()

Размер после очистки: (210, 33)

,event_id,event_time,source_channel,activity_type,course,placement,creative_text,external_or_internal,post_url,views,...,raw_promo_candidate,raw_offer_flag,raw_discount_flag,raw_launch_flag,raw_lead_magnet_flag,raw_ad_marking,raw_erid,raw_scraped_at,raw_html_ref,Unnamed: 34
0,INT-1764,2026-07-01 18:10:49,@postypashki_old,Контент с предложением курсов (авто),ML старт | Data Science,postypashki_old/1764,Самые интересные события в ближайшее время.\nВ...,internal,https://t.me/postypashki_old/1764,21200,...,NaN,1.0,0.0,0.0,0.0,NaN,False,2026-07-01T15:10:49+00:00,NaN,NaN
1,INT-1765,2026-07-02 18:31:22,@postypashki_old,Прочий контент (авто),NaN,postypashki_old/1765,"В новом ролике обсудим, что с вашей психикой с...",internal,https://t.me/postypashki_old/1765,17500,...,NaN,0.0,0.0,0.0,0.0,NaN,False,2026-07-02T15:31:22+00:00,NaN,NaN
2,INT-1767,2026-07-04 12:03:55,@postypashki_old,Промо со скидкой (авто),NaN,postypashki_old/1767,❗️ Завтра заканчивается донабор на стажировку ...,internal,https://t.me/postypashki_old/1767,18600,...,NaN,1.0,1.0,0.0,0.0,NaN,False,2026-07-04T09:03:55+00:00,NaN,NaN
3,INT-1768,2026-07-04 15:35:53,@postypashki_old,Контент с предложением курсов (авто),ML старт,postypashki_old/1768,Академия Авито и Буткем Авито \n\nСегодня прош...,internal,https://t.me/postypashki_old/1768,20400,...,NaN,1.0,0.0,0.0,0.0,NaN,False,2026-07-04T12:35:53+00:00,NaN,NaN
4,INT-1770,2026-07-05 16:51:14,@postypashki_old,Прочий контент (авто),ML старт,postypashki_old/1770,Как затащить МЛ собеседование в 2026 году \n\n...,internal,https://t.me/postypashki_old/1770,19000,...,NaN,0.0,1.0,0.0,0.0,NaN,False,2026-07-05T13:51:14+00:00,NaN,NaN

In [6]:
marketing.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 210 entries, 0 to 209
Data columns (total 33 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   event_id              210 non-null    object
 1   event_time            210 non-null    object
 2   source_channel        210 non-null    object
 3   activity_type         210 non-null    object
 4   course                35 non-null     object
 5   placement             210 non-null    object
 6   creative_text         193 non-null    object
 7   external_or_internal  210 non-null    object
 8   post_url              210 non-null    object
 9   views                 210 non-null    int64
 10  reactions             189 non-null    float64
 11  data_source           210 non-null    object
 12  confidence            210 non-null    object
 13  collected_by          210 non-null    object
 14  notes                 210 non-null    object
 15  channel_relationship  210 non-null    object
 16  paid_status           210 non-null    object
 17  raw_origin            210 non-null    object
 18  raw_category          210 non-null    object
 19  raw_period            97 non-null     object
 20  raw_media             47 non-null     object
 21  raw_forwarded_from    49 non-null     object
 22  raw_links             113 non-null    object
 23  raw_promo_candidate   113 non-null    float64
 24  raw_offer_flag        97 non-null     float64
 25  raw_discount_flag     97 non-null     float64
 26  raw_launch_flag       97 non-null     float64
 27  raw_lead_magnet_flag  97 non-null     float64
 28  raw_ad_marking        3 non-null      object
 29  raw_erid              210 non-null    object
 30  raw_scraped_at        97 non-null     object
 31  raw_html_ref          113 non-null    object
 32  Unnamed: 34           113 non-null    object
dtypes: float64(6), int64(1), object(26)
memory usage: 54.3+ KB